document.getElementById('header-container').style.backgroundColor = '#00B069'
document.querySelector('.emergency-tasks').style.backgroundColor = '#FF9F84'
document.querySelectorAll('.emergency-tasks div h3')[0].style.backgroundColor = '#A500F3'
document.querySelectorAll('.emergency-tasks div h3')[1].style.backgroundColor = '#A500F3'
document.querySelector('.no-emergency-tasks').style.backgroundColor = '#F9DB5E'
document.querySelectorAll('.no-emergency-tasks div h3')[0].style.backgroundColor = '#232525'
document.querySelectorAll('.no-emergency-tasks div h3')[1].style.backgroundColor = '#232525'